services:
  - type: web
    name: college-website
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api 